name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install podman

      - name: Login
        run: |
          podman login -u xtexChooser -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build
        run: |
          podman build -t caddy .

      - name: Push
        run: |
          podman tag localhost/caddy ghcr.io/xtex-vnet/caddy:latest
          podman push ghcr.io/xtex-vnet/caddy:latest
